# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2017 Dr.-Ing. Patrick Siegl <patrick@siegl.it>

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    make compile
  displayName: 'compile'

- script: |
    make test -C bld.x86_64/
  displayName: 'execute tests'
