version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Get recent repo
          command: 'apt-get update'
      - run:
          name: Installing essential build utils
          command: 'apt-get update && apt-get install -y gcc g++ git make cmake'
      - run:
          name: Creating Build Files
          command: 'make compile'
      - run:
          name: Execute tests
          command: 'make test -C bld.x86_64/'
