version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc'
      - run:
          name: Installing MAKE
          command: 'apt-get update && apt-get install -y make'
      - run:
          name: Creating Build Files
          command: 'make compile'
      - run:
          name: Run
          command: 'make run'
